# This is a basic workflow to help you get started with Actions

name: Dr-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      github_gcp_user_email_id:
        default: "default"
        description: GCP user for running github actions
        type: "string"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.github_gcp_user_email_id }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          Name: "Shivakumar"
        run: |
          echo "My name is $Name"
          echo test, and deploy your project.
  test:
     runs-on: ubuntu-latest
     # needs lets you run jobs sequesntially by leting github know the dependencies rather than running parallely.
     needs: [build]
     steps:
     
     - name: Run test
       run: |
          echo "Running test"
          echo " test ran "
